version: "3.9"
services:
  api:
    container_name: express-api
    build:
      context: .
      dockerfile: Dockerfile
    image: express-api  
    restart: always
    ports:
      - "3001:${SERVER_PORT}"  
